### ISSUE TITLE
`terraform-checks` apply job is limited to assert Active or Blocked status

### ISSUE THREAD

**Issue by DnPlas** [canonical/charmed-kubeflow-workflows#65]
The current implementation assumes that all charms are either going to Blocked or Active status, but misses other states like Waiting. This limits the capacity for applying the modules as the checks won't pass if a charm goes into a different state.

Since the Charming organisation is going to be proposing reusable workflows/actions for testing and validating Terraform modules, the Analytics team decided to do the best effort to test, and wait for the common CI at the expense of not covering these edge cases.

The workaround for now is to skip the `apply` job from the `terraform-checks` for any charm that is not going to Blocked or Active status:

```
  terraform-checks:
    name: Terraform
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/terraform-checks.yaml@main
    with:
      apply: false
```
