### ISSUE TITLE
`get-rocks-modified-and-build-scan-test-publish.yaml` fails in empty repos

### ISSUE THREAD

**Issue by DnPlas** [canonical/charmed-kubeflow-workflows#85]
### Bug Description

There seems to be an issue with the `get-rocks-modified-and-build-scan-test-publish.yaml` workflow. If the repository is empty (does not contain any rockcraft project), the workflow will return the following error:

```
# Run dorny/paths-filter@v2
  with:
    token: ***
    list-files: none
    initial-fetch-depth: 100
Error: Input required and not supplied: filters
``` 

This is caused because we are not passing any `filters` to  the `paths-filter` action used in the workflow.

```
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: ${{ needs.get-all-rock-paths.outputs.paths}}
```

### To Reproduce

Run the workflow in a repository that does not contain any rockcraft project

### Environment

Same as the CI - the environment is actually set by the offending workflow

### Relevant Log Output

```shell
Run dorny/paths-filter@v2
  with:
    token: ***
    list-files: none
    initial-fetch-depth: 100
Error: Input required and not supplied: filters
```

### Additional Context

Caught this error [here](https://github.com/canonical/knative-rocks/actions/runs/11722513356/job/32652225979?pr=1)
