### ISSUE TITLE
Create workflow that has build with cache job

### ISSUE THREAD

**Issue by DnPlas** [canonical/charmed-kubeflow-workflows#87]
### Context

The `canonical/data-platform-workflows/.github/workflows/build_charm.yaml` ([docs here](https://github.com/canonical/data-platform-workflows/blob/main/.github/workflows/build_charm.md)) workflow allows charms to be independently built with charmcraft cache which:

* Reduces build time
* Each charm gets built in their own machine, which prevents collisions with pip
* Uploads `.charm` as artefacts

Some of the team's repositories are having trouble specially because of the above. To resolve the situation, the `build_charm` reusable workflow can be included `on_push` and `on_pull` workflows.

### What needs to get done

Create a common workflow that includes the `build_charm.yaml` workflow. The `publish` and `tests` jobs will depend on it.

The changes will look like this:

```yaml

name: On Pull Request

# On pull_request, we:
# * always publish to charmhub at latest/edge/branchname
# * always run tests

on:
  pull_request:

jobs:

  build:
    name: Build charms
    uses: canonical/data-platform-workflows/.github/workflows/build_charm.yaml@v21.0.0
    strategy:
      fail-fast: false
    with:
      cache: ${{ github.event_name == 'pull_request' }}
      charmcraft-snap-channel: 3.x/edge
      path-to-charm-directory: ./charms/${{ matrix.charm }}
```

For repositories with multiple charms we can use the [`get-charm-paths`](https://github.com/canonical/kubeflow-ci/tree/main/actions/get-charm-paths) action.

### Definition of Done

There is a common workflow that all repositories can use for building charms with cache, charm files are downloadable, and adapts to repositories with multiple charms.
